version: '3.9'

services:
  mongo_db:
    container_name: db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    networks:
      - mern-app
  
  api:
    build: .
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    #environment:
      #PORT: 3000
      #DATABASE_URL: mongodb://mongo_db:27017
    depends_on:
      - mongo_db
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge

volumes:
  mongo_db: 
    driver: local